baseURL: "https://psylink.uber.space/"
languageCode: "en-us"
title: "PsyLink"
uglyurls: true
resourceDir: ".resources"
relativeurls: true
taxonomies:
    tag: tags
params:
    dateFmt: "2006-01-02"
permalinks:
    devlog: log_:slug
markup:
    goldmark:
        extensions:
            typographer: false
        renderer:
            unsafe: true
menu:
    main:
      - name: "Blog"
        url: "/devlog.html"
        weight: 1
      - name: "Code"
        url: "https://codeberg.org/hut/psylink"
        weight: 2
