baseURL: "https://psylink.uber.space/"
languageCode: "en-us"
title: "PsyLink"
resourceDir: ".resources"
relativeurls: true
taxonomies:
    tag: tags
permalinks:
    prototypes: :slug
    circuits: :slug
    boards: :slug
    textiles: :slug
    software: :slug
params:
    dateFmt: "2006-01-02"
markup:
    goldmark:
        extensions:
            typographer: false
        renderer:
            unsafe: true
